### ISSUE TITLE
NGINX fixes

### ISSUE THREAD

**Issue by barbayjuliette** [akolgano/ft_transcendence#35]
If I try to access /friends/randomstuff 
I should get the 404 error page
(same for the other routes)
Now, I get: 
Uncaught SyntaxError: Unexpected token '<'
main.js:1 Uncaught SyntaxError: Unexpected token '<'

Dynamic routes:
/profile/username should redirect to /profile (profile.html). Same redirection as without argument. 

On the /friends page, when I click on the user cards, it redirects me correctly, but when I try to acces it directly with nginx, it doesn't work.

**Comment by barbayjuliette** [comment]
/friends works
/friends/ gives an error.
Same for other routes

**Comment by akolgano** [comment]
On the /friends page, when I click on the user cards, it redirects me correctly, but when I try to acces it directly with nginx, it doesn't work. 

Redirects where? Can you take a screen

**Comment by barbayjuliette** [comment]
On the /friends page, when I click on the user cards, it redirects me correctly to **/profile/username** but when I try to access directly  **/profile/username** with Nginx, it doesn't work.

I can take a screenshot later if it is still not clear. Let me know
