### ISSUE TITLE
Pictures HTTPS

### ISSUE THREAD

**Issue by barbayjuliette** [akolgano/ft_transcendence#45]
When loading any picture: 
Warning on the console:  Mixed Content: The page at 'https://localhost/' was loaded over HTTPS, but requested an insecure element 'http://localhost:8000/media/profile_pictures/default.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html

**Comment by akolgano** [comment]
You can change all frontend requests for https now
