### ISSUE TITLE
Dashboards

### ISSUE THREAD

**Issue by barbayjuliette** [akolgano/ft_transcendence#68]
-  Fix date in graphs: date not correct

-  When no result: text black and aligned to the left, same as when there is not results in the profile

- CSS:

#gameMarginChart {
    width: 600px !important;
    height: 600px !important;
}

/* Game Margin Chart custom size */
#victoryLossChart {
    width: 600px !important;
    height: 600px !important;
}
--> merge this into 1 style. Use one single class to apply this style

.show-chart-btn {
    background: none;
    border: none; /* Remove the border */
    outline: none; /* Remove any default button outline (like when focused) */
    padding: 0;
    color: inherit; /* Inherit the text color from the parent */
    font-size: 1.5rem; /* Adjust the icon size */
    cursor: pointer;
}
--> See if you can replace some of those with BS

.dashboard-container {
	max-width: 800px;
	margin-left: 0; /* Align the container to the left */
}
-->margin-left: change to Bootstrap

<img width="482" alt="Screenshot 2024-10-18 at 14 19 38" src="https://github.com/user-attachments/assets/86181501-0108-4713-8d41-0fcc01fe1a2b">

--> Game duration should be MM:SS

<img width="790" alt="Screenshot 2024-10-18 at 14 21 41" src="https://github.com/user-attachments/assets/6f347ab2-9822-4583-ae5a-5463661628a0">

-->  x and y axis: translation

**Comment by chinwenkai** [comment]
Above amendments done.

**Comment by barbayjuliette** [comment]
@chinwenkai  Can you create a PR with the changes if it is ready? Thanks
