### ISSUE TITLE
Test game

### ISSUE THREAD

**Issue by barbayjuliette** [akolgano/ft_transcendence#80]
Test game, tournament and AI.

The ball gets faster after each paddle bounce, up until a certain point, and reset to default speed after each score.
AI, after a certain speed, the AI is less accurate, so you can actually beat it. Let me know if you manage to score with AI and if you think we should make it easier.

Also test the rest of the site

**Comment by chinwenkai** [comment]
Game and tournament works well. AI works very well. I managed to score a point against AI, but didn't manage to win a game against AI. I think it is ok that AI is difficult to beat.
